export const languagesOptions=[
    {label: 'Amharic', value: 'Amharic'},
    {label: 'Arabic', value: 'Arabic'},
    {label: 'Dutch', value: 'Dutch'},
    {label: 'English', value: 'English'},
    {label: 'German', value: 'German'},
    {label: 'Greek', value: 'Greek'},
    {label: 'Hindi', value: 'Hindi'},
    {label: 'Hungarian', value: 'Hungarian'},
    {label: 'Indonesian', value: 'Indonesian'},
    {label: 'Italian', value: 'Italian'},
    {label: 'Japanese', value: 'Japanese'},
    {label: 'Korean', value: 'Korean'},
    {label: 'French', value: 'French'},
    {label: 'Mandarin', value: 'Mandarin'},
    {label: 'Nepali', value: 'Nepali'},
    {label: 'Norwegian', value: 'Thai'},
    {label: 'Persian', value: 'Persian'},
    {label: 'Polish', value: 'Polish'},
    {label: 'Portuguese', value: 'Portuguese'},
    {label: 'Russian', value: 'Russian'},
    {label: 'Spanish', value: 'Spanish'},
    {label: 'Swahili', value: 'Swahili'},
    {label: 'Swedish', value: 'Swedish'},
    {label: 'Turkish', value: 'Turkish'},
    {label: 'Urdu', value: 'Urdu'},
    {label: 'Vietnamese', value: 'Vietnamese'},
  ]